spring:
  application:
   name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sadhanaNisha/ConfigServerCapston.git

server:
  port: 8888

logging:
 level:
  org:
   springframework: DEBUG
